CREATE DATABASE Job_Database;

CREATE TABLE tasks (
  task_ID INT(10) UNSIGNED AUTO_INCREMENT PRIMARY KEY NOT NULL,
  task_Name VARCHAR(255) NOT NULL,  
  date DATE NOT NULL,
  location VARCHAR(255) NOT NULL,
  details VARCHAR(255) NOT NULL,
  payment_Amount DECIMAL (10, 2) NOT NULL,  
  created at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);